k8s:
   whitelist_deployment_names: ["nginx-deployment"]
   control:
      userdata: {"deployment":"nginx-ref"}
   application:
      components:
         nginx-deployment:
            settings: {"replicas": {"min": 1, "value": 1, "type": "range", "step": 1, "max": 3},
                       "EVAR": {"type":"range", "min":1, "max":100, "step":1, "default":20}}
